### ISSUE TITLE
raise Exception('Error: Invalid box type: %s' % box)

### ISSUE THREAD

**Issue by WangZZJJ** [linxuewu/Sparse4D#59]
2024-07-08T14:00:20.858620949Z Loaded ground truth annotations for 6019 samples.
2024-07-08T14:00:21.030217541Z Filtering tracks
2024-07-08T14:00:21.030556548Z Traceback (most recent call last):
2024-07-08T14:00:21.030567733Z   File "./tools/train.py", line 319, in <module>
2024-07-08T14:00:21.030708329Z     main()
2024-07-08T14:00:21.030718795Z   File "./tools/train.py", line 294, in main
2024-07-08T14:00:21.030751728Z     custom_train_model(
2024-07-08T14:00:21.030758649Z   File "/ml-engine/code/sparse4d-v3/projects/mmdet3d_plugin/apis/train.py", line 29, in custom_train_model
2024-07-08T14:00:21.030788541Z     custom_train_detector(
2024-07-08T14:00:21.030797541Z   File "/ml-engine/code/sparse4d-v3/projects/mmdet3d_plugin/apis/mmdet_train.py", line 219, in custom_train_detector
2024-07-08T14:00:21.030843389Z     runner.run(data_loaders, cfg.workflow)
2024-07-08T14:00:21.030876659Z   File "/opt/conda/envs/mm_sparse4d/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 144, in run
2024-07-08T14:00:21.030890559Z     iter_runner(iter_loaders[i], **kwargs)
2024-07-08T14:00:21.030898151Z   File "/opt/conda/envs/mm_sparse4d/lib/python3.8/site-packages/mmcv/runner/iter_based_runner.py", line 70, in train
2024-07-08T14:00:21.030907128Z     self.call_hook('after_train_iter')
2024-07-08T14:00:21.030914039Z   File "/opt/conda/envs/mm_sparse4d/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 317, in call_hook
2024-07-08T14:00:21.030963458Z     getattr(hook, fn_name)(self)
2024-07-08T14:00:21.030972758Z   File "/opt/conda/envs/mm_sparse4d/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 266, in after_train_iter
2024-07-08T14:00:21.031000297Z     self._do_evaluate(runner)
2024-07-08T14:00:21.031007438Z   File "/opt/conda/envs/mm_sparse4d/lib/python3.8/site-packages/mmdet/core/evaluation/eval_hooks.py", line 63, in _do_evaluate
2024-07-08T14:00:21.031033978Z     key_score = self.evaluate(runner, results)
2024-07-08T14:00:21.031041173Z   File "/opt/conda/envs/mm_sparse4d/lib/python3.8/site-packages/mmcv/runner/hooks/evaluation.py", line 367, in evaluate
2024-07-08T14:00:21.031079651Z     eval_res = self.dataloader.dataset.evaluate(
2024-07-08T14:00:21.031084892Z   File "/ml-engine/code/sparse4d-v3/projects/mmdet3d_plugin/datasets/nuscenes_3d_det_track_dataset.py", line 589, in evaluate
2024-07-08T14:00:21.031154730Z     ret_dict = self._evaluate_single(
2024-07-08T14:00:21.031158960Z   File "/ml-engine/code/sparse4d-v3/projects/mmdet3d_plugin/datasets/nuscenes_3d_det_track_dataset.py", line 499, in _evaluate_single
2024-07-08T14:00:21.031203155Z     nusc_eval = TrackingEval
2024-07-08T14:00:21.031206816Z   File "/opt/conda/envs/mm_sparse4d/lib/python3.8/site-packages/nuscenes/eval/tracking/evaluate.py", line 97, in __init__
2024-07-08T14:00:21.031252699Z     pred_boxes = filter_eval_boxes(nusc, pred_boxes, self.cfg.class_range, verbose=verbose)
2024-07-08T14:00:21.031256982Z   File "/opt/conda/envs/mm_sparse4d/lib/python3.8/site-packages/nuscenes/eval/common/loaders.py", line 219, in filter_eval_boxes
2024-07-08T14:00:21.031295552Z     class_field = _get_box_class_field(eval_boxes)
2024-07-08T14:00:21.031299258Z   File "/opt/conda/envs/mm_sparse4d/lib/python3.8/site-packages/nuscenes/eval/common/loaders.py", line 283, in _get_box_class_field
2024-07-08T14:00:21.031333192Z     raise Exception('Error: Invalid box type: %s' % box)
2024-07-08T14:00:21.031336949Z Exception: Error: Invalid box type: None

**Comment by sdc-sdd** [comment]
Have you solved it yet？

**Comment by lkh618** [comment]
Hi, I've encountered the same issue before. I think the main reason for this problem is: in the early stages of training, none of the predicted bounding boxes have high confidence scores, which results in no predicted boxes being included in the tracking evaluation when using nuscenes-devkit. I have two solutions:
1. In the config file, increase the 'interval' value in the evaluation parameter to ensure evaluation only occurs after the model has somewhat converged.
2. During training, decrease the 'tracking_threshold' value in the config file to guarantee that some instances participate in tracking evaluation even in early training stages. However, this might cause the tracking metrics in validation to appear lower than the model's actual tracking performance.
You could also modify the nuscenes-devkit source code to address this issue, but I wouldn't recommend doing that.
