### ISSUE TITLE
How did you get nuscenes_cam and the pkl files inside?

### ISSUE THREAD

**Issue by myn1szh** [linxuewu/Sparse4D#64]
When try to load train.pkl,i got errors:

loading ann_file = <_io.BufferedReader name='**data/nuscenes_cam/nuscenes_infos_train.pkl'**>
Traceback (most recent call last):
  File "/usr/local/lib64/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/Sparse4D/projects/mmdet3d_plugin/datasets/nuscenes_3d_det_track_dataset.py", line 142, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/site-packages/mmdet3d/datasets/custom_3d.py", line 88, in __init__
    self.data_infos = self.load_annotations(open(local_path, 'rb'))
  File "/Sparse4D/projects/mmdet3d_plugin/datasets/nuscenes_3d_det_track_dataset.py", line 484, in load_annotations
    data = mmcv.load(ann_file)
  File "/usr/local/lib64/python3.8/site-packages/mmcv/fileio/io.py", line 51, in load
    raise TypeError(f'Unsupported format: {file_format}')
TypeError: Unsupported format: None

**Comment by wzh506** [comment]
me,too

**Comment by 42nick** [comment]
Same issue here.
